/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mendykjanniktontauben;

import java.awt.Graphics;

/**
 *
 * @author Jannik.Mendyk
 */
public class Oberflaeche extends javax.swing.JPanel {

    /**
     * Creates new form GUI
     */
    
     
    private int xFK;
    private int yFK;

    Steuerung steuerung;
    Fadenkreuz FK;
    
    public Oberflaeche() {
        steuerung = new Steuerung(this);
        FK = new Fadenkreuz(this);
        setFocusable(true);
        requestFocus();
        initComponents();
    }
    
    
    public void geklicktMaus(){
       
       steuerung.feuer(xFK, yFK);
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g); 
        zeichnen(g);
    }
    
    public void zeichnen(Graphics g){       
        steuerung.zeichneAlleTt(g);
        FK.zeichnen(g);
    }
    
    
    public void zeigeBildFertig(){
        
    }
    
    public void spielStart(){
        steuerung.starteSpiel();
    }
    
    public void aktualisiereOberflaeche(){
        repaint();
    }
    
    
    public int gibXFK(){
        
        return xFK;
    }
    
    public int gibYFK(){
        
        return yFK;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        geklicktMaus();
        System.out.println("klick");
        this.xFK=evt.getX();
        this.yFK=evt.getY();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        this.yFK = evt.getY();
        this.xFK = evt.getX();
        FK.setX();
        FK.setY();
    }//GEN-LAST:event_formMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
